export const gray = '#f6f8fa'
export const white = '#fff'
export const shadowBlue = '#3a7fe7'
export const softBlue = '#4c93ff'
export const textGray = '#191b26'
export const textGrayLight = '#8e8f93'
export const dangerRed = '#ea6e5e'
